esphome:
  name: esp32-c6
  friendly_name: ESP32-C6-XIAO
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L
    board_build.flash_size: 4MB
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.2.1
    platform_version: 6.7.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      # CONFIG_RMT_SUPPRESS_DEPRECATE_WARN: y

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_encryption_key

ota:
 - platform: esphome
   password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Esp Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:

# status_led:
#   pin: GPIO15

light:
  - platform: rgb
    id: rgb_light
    name: "Sunset Light"
    red: output_red
    green: output_green
    blue: output_blue
  


output:
  - platform: ledc
    id: output_red
    pin: GPIO21
    frequency: 500Hz
  - platform: ledc
    id: output_green
    pin: GPIO22
    frequency: 500Hz
  - platform: ledc
    id: output_blue
    pin: GPIO23
    frequency: 500Hz

remote_receiver:
  pin: 
    number: GPIO0
    inverted: true
  dump: lg
  rmt_channel: 2


binary_sensor:
  - platform: remote_receiver
    name: "turn on"
    lg:
      data: "0x00F7C03F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on: "rgb_light"
  - platform: remote_receiver
    name: "turn off"
    lg:
      data: "0x00F740BF"
      nbits: 32
    on_press:
      then: 
       - light.turn_off: "rgb_light"
  - platform: remote_receiver
    name: "increase brightness"
    lg:
      data: "0x00F700FF"
      nbits: 32
    on_press:
      then: 
       - light.dim_relative:
          id: rgb_light
          relative_brightness: 5%
  - platform: remote_receiver
    name: "lower brightness"
    lg:
      data: "0x00F7807F"
      nbits: 32
    on_press:
      then: 
       - light.dim_relative:
          id: rgb_light
          relative_brightness: -5%
  - platform: remote_receiver
    name: "full red"
    lg:
      data: "0x00F720DF"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
          id: rgb_light
          red: 1
          green: 0
          blue: 0
- platform: remote_receiver
    name: "full green"
    lg:
      data: "0x00F7A05F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
          id: rgb_light
          red: 0
          green: 1
          blue: 0
- platform: remote_receiver
    name: "full blue"
    lg:
      data: "0x00F7609F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
          id: rgb_light
          red: 0
          green: 0
          blue: 1
- platform: remote_receiver
    name: "full blue"
    lg:
      data: "0x00F7609F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 0
        green: 0
        blue: 1
- platform: remote_receiver
    name: "full white"
    lg:
      data: "0x00F7609F"
      nbits: 32
    on_press:
      then: 
       
- light.turn_on:
        id: rgb_light
        red: 1
        green: 1
        blue: 1
- platform: remote_receiver
    name: "rgb_red"
    lg:
      data: "0x00F710EF"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 1
        green: 0
        blue: 0
- platform: remote_receiver
    name: "rgb_tangerine"
    lg:
      data: "0x00F730CF"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 100%
        green: 21%
        blue: 5%
- platform: remote_receiver
    name: "rgb_melon"
    lg:
      data: "0x00F708F7"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 100%
        green: 49%
        blue: 5%
- platform: remote_receiver
    name: "rgb_yellow"
    lg:
      data: "0x00F728D7"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 100%
        green: 100%
        blue: 0%
- platform: remote_receiver
    name: "rgb_green"
    lg:
      data: "0x00F7906F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 5%
        green: 100%
        blue: 5%
- platform: remote_receiver
    name: "rgb_baby_blue"
    lg:
      data: "0x00F7B04F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 0%
        green: 100%
        blue: 100%
- platform: remote_receiver
    name: "rgb_turquoise"
    lg:
      data: "0x00F78877"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 15%
        green: 50%
        blue: 100%
- platform: remote_receiver
    name: "rgb_blue_light"
    lg:
      data: "0x00F7A857"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 5%
        green: 30%
        blue: 100%
- platform: remote_receiver
    name: "rgb_blue_dark"
    lg:
      data: "0x00F750AF"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 0%
        green: 5%
        blue: 100%
- platform: remote_receiver
    name: "rgb_purple_dark"
    lg:
      data: "0x00F7708F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 25%
        green: 2%
        blue: 100%
- platform: remote_receiver
    name: "rgb_purple_medium"
    lg:
      data: "0x00F748B7"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 45%
        green: 0%
        blue: 100%
- platform: remote_receiver
    name: "rgb_purple_light"
    lg:
      data: "0x00F76897"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        red: 100%
        green: 0%
        blue: 100%
- platform: remote_receiver
    name: "flash"
    lg:
      data: "0x00F7D02F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        effect: 
          flicker:
- platform: remote_receiver
    name: "strobe"
    lg:
      data: "0x00F7F00F"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        effect: 
          strobe:
- platform: remote_receiver
    name: "fade"
    lg:
      data: "0x00F7C837"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        effect:
          pulse:
- platform: remote_receiver
    name: "smooth"
    lg:
      data: "0x00F7E817"
      nbits: 32
    on_press:
      then: 
       - light.turn_on:
        id: rgb_light
        effect:
          pulse:
            update__interval: 5s
