esphome:
  name: esp32-c6
  friendly_name: ESP32-C6-XIAO
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L
    board_build.flash_size: 4MB
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.2.1
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_RMT_SUPPRESS_DEPRECATE_WARN: y

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Esp Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:

status_led:
  pin: GPIO15

light:
  - platform: rgb
    name: "Sunset Light"
    red: output_red
    green: output_green
    blue: output_blue
  


output:
  - platform: ledc
    id: output_red
    pin: GPIO21
    frequency: 500Hz
  - platform: ledc
    id: output_green
    pin: GPIO22
    frequency: 500Hz
  - platform: ledc
    id: output_blue
    pin: GPIO23
    frequency: 500Hz

# remote_receiver:
#   pin: GPIO0
#   dump: raw